config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :camps do
    resources :activities
  end

  resources :activities do
    resources :assignments
  end

  resources :comments , only: [:new, :create]

  resources :assignments

  resources :camp_counselors do
    resources :assignments, only: [:show, :index]
    resources :comments, shallow: true
  end


  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/camp_counselor.rb
class CampCounselor < ApplicationRecord
  has_secure_password
  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :assignments
  has_many :activities, through: :assignments

  has_many :camps, through: :assignments

  has_many :comments
  # look into this improvement suggestion from Jennifer (Jenn) Hansen during my rails project assessment:
  has_many :commented_activities, through: :comments, source: :activity
  # maybe source: :activities


end

app/controllers/camp_counselors_controller.rb
class CampCounselorsController < ApplicationController
  skip_before_action :require_log_in, only: [:new, :create]
  before_action :set_counselor, only: [:show, :edit, :update, :destroy]
  include CampCounselorsHelper

  def new
    @counselor = CampCounselor.new
  end

  def create
    @counselor = CampCounselor.create(counselor_params)
    if @counselor.save
      session[:user_id] = @counselor.id
      redirect_to camp_counselor_path(@counselor)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @counselor.update(counselor_params)
      redirect_to camp_counselor_path(@counselor)
    else
      render :edit
    end
  end

  def destroy
    @counselor.destroy
    redirect_to signin_path
  end


  private

  def set_counselor
    @counselor = CampCounselor.find_by(id: session[:user_id])
  end

  def counselor_params
    params.require(:camp_counselor).permit(:name, :email, :age, :admin, :uid, :provider, :password)
  end
end

app/helpers/camp_counselors_helper.rb
module CampCounselorsHelper

  def camp_name(activity)
    Camp.find_by(id: activity.camp_id).name
  end

end

app/views/camp_counselors/_counselor.html.erb
<h3><%= counselor.name %></h3>

<p>
  Email: <%= counselor.email %>
  <br>
  Age: <%= counselor.age %>
  <br>
  <br>
  <br>
  <% if counselor.admin %>
  <em><%= "You have a Camp Admin account" %></em>
  <% end %>
  <br>
  <%= link_to "Edit Your Profile", edit_camp_counselor_path(:current_user) %>
  <br>
  <br>
  <br>
  <br>
  Here are the activities you signed up for:
  <br>
  <% if counselor.activities %>
    <% counselor.activities.each do |activity| %>
      <br>
      <strong><em><%= activity.name %></em></strong>
      <br>
      <%= camp_name(activity) %>
      <br>
      <%= activity.description %>
      <br>
    <% end %>
  <% else %>
    You have not signed up for any activities yet...
  <% end %>
  <br>
  <%= link_to "View All Your Assignments", camp_counselor_assignments_path(counselor) %>
  <br>
  <br>
  <br>
  <br>
  Camps you are associated with:
  <br>
  <% counselor.camps.uniq.each do |camp| %>
    <br>
    <strong><em><%= camp.name %></em></strong>
    <br>
    <%= camp.location %>
    <br>
  <% end %>
</p>
<br>
<br>

app/views/camp_counselors/_form.html.erb
<%= form_for counselor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <br>
  <br>
  <%= f.label(:admin, "Camp Admin") %><br>
  <%= f.radio_button(:admin, true) %>Yes
  <%= f.radio_button(:admin, false) %>No
  <br><br>
  <%= f.submit %>
<% end %>
<br>
<%= form_for :camp_counselor, url: camp_counselor_path, method: :delete, data: {confirm: "Are You Sure You Want to Delete Your Account?"} do |f| %>
<%= f.submit "Delete Account" %>
<% end %>

app/views/camp_counselors/_new_counselor.html.erb
<%= form_for counselor do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :email %>
  <br>
  <%= f.text_field :email %>
  <br>
  <br>
  <%= f.label :age %>
  <br>
  <%= f.text_field :age %>
  <br>
  <br>
  <%= f.label(:admin, "Camp Admin") %><br>
  <%= f.radio_button(:admin, true) %>Yes
  <%= f.radio_button(:admin, false) %>No
  <br>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <br>
  <%= f.password_field :password_confirmation %>
  <br>
  <br>
  <%= f.submit "Create Profile" %>
<% end %>

app/views/camp_counselors/edit.html.erb
<h2>Update Your Camp Counselor Profile:</h2>
<br>

<%= render partial: 'layouts/flash_notice', locals: {object: @counselor}%>

<br>
<div id="form">
<%= render partial: 'form', locals: {counselor: @counselor} %>
</div>

app/views/camp_counselors/new.html.erb
<h2>Create Your Camp Counselor Profile:</h2>
<br>

<%= render partial: 'layouts/flash_notice', locals: {object: @counselor}%>

<br>
<div id="form">
  <%= render partial: 'new_counselor', locals: {counselor: @counselor} %>
</div>

app/views/camp_counselors/show.html.erb
<h2>Camp Counselor Profile Page</h2>
<br>
<div class="subtext">
  <%= render partial: 'counselor', locals: {counselor: @counselor} %>
</div>