config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :camps do
    resources :activities
  end

  resources :activities do
    resources :assignments
  end

  resources :comments , only: [:new, :create]

  resources :assignments

  resources :camp_counselors do
    resources :assignments, only: [:show, :index]
    resources :comments, shallow: true
  end


  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/camp.rb
class Camp < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :location
  validates_presence_of :description

  has_many :activities
  has_many :comments, through: :activities

  has_many :assignments
  has_many :camp_counselors, through: :assignments

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]
  include CampsHelper

  def index
    @camps = Camp.all
  end

  def show
  end

  def new
    @camp = Camp.new
  end

  def create
    @camp = Camp.create(camp_params)
    if @camp.save
      redirect_to camp_path(@camp)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @camp.update(camp_params)
      redirect_to @camp
    else
      render :edit
    end
  end


  private

  def set_camp
    @camp = Camp.find_by(id: params[:id])
  end

  def camp_params
    params.require(:camp).permit(:name, :location, :description)
  end

end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_camp_list.html.erb
<% camps.each do |camp| %>
  <h3 style="font-weight:500;"><%= camp.location %></h3>
    <p>
    <strong>
      <%= link_to camp.name, camp_path(camp) %>
    </strong>
    <br>
    <br>
    <%= camp.description %>
    <br>
    <br>
    <br>
    </p>
<% end %>

app/views/camps/_new_camp.html.erb
<%= form_for camp do |f| %>
  <%= f.label :name, "Camp Name" %>
  <br>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :location, "Location" %>
  <br>
  <%= f.text_field :location %>
  <br>
  <br>
  <%= f.label :description, "Description" %>
  <br>
  <%= f.text_area :description, size: "50x10" %>
  <br>
  <br>
  <%= f.submit "Add Camp" %>
<% end %>

app/views/camps/index.html.erb
<h2>Camps</h2>
<br>
<%= render partial: 'camp_list', locals: {camps: @camps} %>

app/views/camps/new.html.erb
<h2>Add a New Camp:</h2>
<br>

<%= render partial: 'layouts/flash_notice', locals: {object: @camp}%>

<br>
<div id="form">
  <%= render partial: 'new_camp', locals: {camp: @camp} %>
</div>

app/views/camps/show.html.erb
<h2><%= @camp.name %></h2>
<br>
<div class="subtext">
<h3><%= @camp.location %></h3>
<%= @camp.description %>
</div>
<br>
<br>
<strong><em>Camp Counselors already signed up:</em></strong>
<br>
<% @camp.camp_counselors.uniq.each do |counselor| %>
  <%= counselor.name %>
  <br>
<% end %>
<br>
<br>
<p style="text-align:center;">
  <%= link_to "View #{@camp.name} Activities", camp_activities_path(@camp) %>
</p>