config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :camps do
    resources :activities
  end

  resources :activities do
    resources :assignments
  end

  resources :comments , only: [:new, :create]

  resources :assignments

  resources :camp_counselors do
    resources :assignments, only: [:show, :index]
    resources :comments, shallow: true
  end


  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/activity.rb
class Activity < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :description

  has_many :comments

  has_many :assignments
  has_many :camp_counselors, through: :assignments

  belongs_to :camp

  def self.sorted_asc
    order(name: :asc)
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  include ActivitiesHelper

  def index
    if params[:camp_id]
      @camp = Camp.find_by(id: params[:camp_id]) if params[:camp_id]
      @activities = @camp.activities.sorted_asc
    else
      @activities = Activity.all.sorted_asc
    end
  end

  def show
    @assignments = @activity.assignments.order_by_filled
    @comments = @activity.comments
  end

  def new
    @camp = Camp.find_by(id: params[:camp_id]) if params[:camp_id]
    @activity = Activity.new
  end

  def create
    create_logic
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to @activity
    else
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end


  private

  def set_activity
    @activity = Activity.find_by(id: params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :description, :camp_id)
  end

  def create_logic
    @activity = Activity.create(activity_params)
    if @activity.save
      2.times do
        @activity.assignments.create(:activity_id => @activity.id, :camp_id => @activity.camp_id, :filled => false, :rating => 0)
      end
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activity_delete_link
    if current_user.admin
       link_to "Delete Activity", @activity, method: :delete, data: { confirm: "Delete This Activity?" }
    end
  end

  def activity_edit_link
    if current_user.admin
      link_to "Edit this Activity", edit_activity_path(@activity)
    end
  end

  def activity_index_header
    if @camp
      "#{@camp.name} Activities"
    else
      "Activities"
    end
  end

end

app/views/activities/_activity_availability.html.erb
<% assignments.each do |assignment| %>
  <em>
    <% if assignment.filled %>
      <%= "One assignment is full" %>
      <br>
    <% else %>
      <%= form_for assignment do |f|  %>
      <%= f.hidden_field :camp_counselor_id, :value => current_user.id  %>
      <%= f.hidden_field :filled, :value => true  %>
      <%= f.submit "Take this assignment"  %>
      <% end  %>
    <% end  %>
  </em>
<% end %>
<br>

app/views/activities/_activity_comments.html.erb
What others have to say about <%= activity.name %>:
<br>
<br>
<br>
<div style="text-align:center; color:grey">
  <% comments.each do |comment| %>
    <strong><%= comment.title %></strong>
    <br>
    <em>"<%= comment.content %>"</em>
    <br>
    <% if comment.camp_counselor_id %>
    <em style="font-size:12px; color:black">
    posted by: <%= CampCounselor.find_by(id: comment.camp_counselor_id).name %>
    </em>
    <br>
    <% end %>
    <br>
    <br>
  <% end %>
</div>

app/views/activities/_activity_list.html.erb
<p style="text-align:center;"><%= link_to "Add New Activity", new_activity_path %>
</p>
<br>
<% activities.each do |activity| %>
    <p>
      <%= link_to "#{activity.name}", activity_path(activity) %>
      <br>
      <br>
      <%= activity.description %>
      <br>
      <span style="font-size:14px;">Fun Rating: <%= activity.assignments.average(:rating) %></span>
      <br>
      <br>
      <em><%= link_to "#{activity.camp.name}", camp_path(activity.camp) %></em>
      <br>
      <br>
    </p>
  <br>
<% end %>

app/views/activities/_edit_activity.html.erb
<%= form_for activity do |f| %>
  <br>
  <br>
  <em>
  <%= f.label :description, "Description:" %>
  </em>
  <br>
  <%= f.text_area :description %>
  <br>
  <br>
  <%= f.submit "Update Activity" %>
<% end %>
<br>
<%= form_for :activity, url: activity_path, method: :delete, data: {confirm: "Are You Sure You Want to Delete This Activity?"} do |f| %>
<%= f.submit "Delete Activity" %>
<% end %>

app/views/activities/_new_activity.html.erb
<%= form_for activity do |f| %>
  <%= f.label :name, "Activity Name" %>
  <%= f.text_field :name %>
  <br>
  <% if @camp %>
    <%= f.hidden_field :camp_id, value: @camp.id %>
  <% else %>
    <%= f.label :camp_id, "Camp name:" %><br>
    <%= f.collection_select :camp_id, Camp.all, :id, :name, :include_blank => "Please select" %>
    <br>
  <% end %>
  <%= f.label :description, "Description" %>
  <br>
  <%= f.text_area :description, size: "50x10" %>
  <br>
  <%= f.submit "Create Activity" %>
<% end %>

app/views/activities/edit.html.erb
<h2>Update <%= @activity.name %> Activity</h2>
<br>

<%= render partial: 'layouts/flash_notice', locals: {object: @activity} %>

<div id="form">
  <%= render partial: 'edit_activity', locals: {activity: @activity} %>
</div>

app/views/activities/index.html.erb
<h2><%= activity_index_header %></h2>
<br>
<%= render partial: 'activity_list', locals: {activities: @activities} %>

app/views/activities/new.html.erb
<h2>Create a New Activity:</h2>
<br>

<%= render partial: 'layouts/flash_notice', locals: {object: @activity} %>

<br>
<div id="form">
  <%= render partial: 'new_activity', locals: {activity: @activity} %>
</div>

app/views/activities/show.html.erb
<h3 style="text-align:center; font-weight:400;"><%= @activity.camp.name %></h3>
<h2><%= @activity.name %></h2>

<div style="text-align:center">
  <%= activity_edit_link %>
</div>
<br>
<br>
<h3><%= @activity.description %></h3>
<p>
  Fun Rating: <%= @activity.assignments.average(:rating) %>
  <br>
</p>
Availability:
<br>
<%= render partial: 'activity_availability', locals: {assignments: @assignments} %>
<br>
<br>
Counselors that are signed up for this activity:
<br>
<% @activity.camp_counselors.uniq.each do |counselor| %>
  <em><%= counselor.name %></em>
  <br>
<% end %>
<br>
<br>
<br>
<%= render partial: 'activity_comments', locals: {activity: @activity, comments: @comments} %>
<br>
<br>
<br>
Share your comments about <%= @activity.name %>:
<br>
<div class="notice">
  <%= flash[:notice] %>
</div>
<br>
<div id="form">
  <%= render :partial => 'comments/form', locals: {activity: @activity} %>
</div>
<br>
<br>