config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :camps do
    resources :activities
  end

  resources :activities do
    resources :assignments
  end

  resources :comments , only: [:new, :create]

  resources :assignments

  resources :camp_counselors do
    resources :assignments, only: [:show, :index]
    resources :comments, shallow: true
  end


  get '/auth/facebook/callback' => 'sessions#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/views/layouts/_flash_notice.html.erb
<div class="notice">
  <% object.errors.full_messages.each do | message | %>
  <%= message %>
  <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Camptivities</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<header class="header">
      Camptivities
    <h4 style="text-align:center; font-weight:300; font-size:16px; letter-spacing: 3px;">
      CONNECTING CAMP COUNSELORS WITH CAMP ACTIVITIES
    </h4>
    </header>
		<nav>
      <% if logged_in? %>
        <%= link_to "Camps", camps_path %>
        <%= link_to "Activities", activities_path %>
        <%= link_to "Assignments", assignments_path %>
        <%= link_to "My Profile", camp_counselor_path(:current_user) %>
        <% if current_user.admin %>
        <%= link_to "Create Activity", new_activity_path %>
        <%= link_to "Add Camp", new_camp_path %>
        <% end %>
        <em><%= link_to "Log Out", logout_path %></em>
        <br>
      <% end %>
		</nav>
    <main>
      <section class="todoapp">
        <%= yield %>
      </section>
    </main>
  </body>
</html>